#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title:
    en: Resume of KunYi
    zh: 簡歷：陳坤毅
email: kunyi.chen@gmail.com
description:
    en: KunYi's Resume
    zh: 坤毅的簡歷
baseurl: "/resume" # the subpath of your site, e.g. /blog
url: "https://kunyi.github.io" # the base hostname & protocol for your site, e.g. http://example.com
plugins:
    - jekyll-assets
    - autoprefixer-rails 

copyright: All rights reserved.

navigation: navigation

# --
# Jekyll assets settings
# --
assets:
    cache: false
    gzip: nil
    sources:
        - _assets/css
        - _assets/fonts
        - _assets/images
        - _assets/videos
        - _assets/javascript
        - _assets/video
        - _assets/image
        - _assets/img
        - _assets/js

    plugins:
        css: { autoprefixer: {}}
        img: { optim: {}}

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
